Add index.html and style.css file to the desktop version
Etsubdink-Demeke/portifolio-desktop-version pull request #1
Opened 2023-05-05 18:17 UTC by Etsubdink-Demeke

This pull request is created to the desktop version of my portifolio for adding the index.html,the style.css and all the other resourses.

2023-05-05 19:34 UTC, stanleySimeon requested changes
Hi @Etsubdink-Demeke

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# ⚠️ Invalid Code Review Request ⚠️ 

You have submitted a project, that does not have a descriptive Pull Request (PR). The PR descriptions should contain a summary of the changes you have in the project/PR. This gives the reviewer an idea of the changes that took place in this particular PR. Kindly fix this before requesting another review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @stanleySimeon in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-05 20:24 UTC, wickathou requested changes
Hi @Etsubdink-Demeke  , 

>You are almost there!
Great effort so far, but unfortunately there are some issues that you need to review in order to get your project approved, but you got this!

![test](https://raw.githubusercontent.com/wickathou/client-assets/main/end-design/code-reviews/sorry.gif)
>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
[Optional] Your CSS file has multiple selectors that repeatedly use the `font-family: 'Poppins', sans-serif;` property to assign the font to individual parts of your code. To keep your code DRY, consider using a global selector `*` as your template uses 'Poppins on all parts of the design

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
<br/>
### Consider also:
- Exploring why initiating your project with `npm init` is a good practice
<br/>

## Highlights
- Interesting use of the `position: fixed` property on your navbar 🏅
- Using a license in the project 💯
- Descriptive commit messages ✨
<br/>
Feel free to leave any questions or comments in the PR thread mentioning me so I can see the notification and reply `@wickathou`.

You can also try reaching me on Slack, looking for me as `@Javier Hernandez`

Cheers and Happy coding!👏👏👏
<br/>
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 20:24 UTC, wickathou commented on index.html
> +            <div class="screenshoot"><img src="images/Portoflio Card/Snapshoot Portfolio.jpg"></div>
- [ ] **Required:** Your work section background has a different color and the presentation of the cards in your design has difference on their proportions to the figma design

Your design
![image](https://user-images.githubusercontent.com/50066876/236558095-30e6dc8d-e6c4-4129-8808-b251d3220c51.png)

Figma design
![image](https://user-images.githubusercontent.com/50066876/236558174-9acc101a-1263-4f2b-b3b4-bd50b7663a4b.png)

2023-05-05 20:24 UTC, wickathou commented on index.html
> +                <li>2015</li>
- [ ] **Required:** These elements have a different color on the figma design, please update it to match the figma file

Your design
![image](https://user-images.githubusercontent.com/50066876/236558535-14871d7b-d2ef-4e85-b49d-5439e586a10b.png)


Figma design
![image](https://user-images.githubusercontent.com/50066876/236558479-001786dd-38e4-4ee4-8610-9cb330d70d7c.png)

2023-05-05 20:24 UTC, wickathou commented on index.html
> +        <button>Get my resume</button>
- [ ] **Required:** Your buttons across the site don't look like the figma design, update it to match the provided design

- [ ] **Required** The 'LET's CONNECT' link has a different font and color to the one provided, please update it to match the figma design

Your design
![image](https://user-images.githubusercontent.com/50066876/236559168-f56cf274-fdb8-4085-a538-4cea89f5605a.png)

Figma design
![image](https://user-images.githubusercontent.com/50066876/236559229-a823ce39-0a0e-4ce8-83d8-0387d287e21e.png)

2023-05-05 20:24 UTC, wickathou commented on index.html
> +    </section>
- [ ] **Required:** Your 'contact me' section has a different alignment to the one shown on the figma design and the blue background has a larger height than the figma design

Your design
![image](https://user-images.githubusercontent.com/50066876/236559715-4d9487b9-4d1f-42df-9f23-a7deea00b25f.png)

Figma design
![image](https://user-images.githubusercontent.com/50066876/236559974-a872debb-68c2-439d-9658-37589a32063d.png)

2023-05-05 20:24 UTC, wickathou commented on index.html
> +      </header>
[Optional] The sticky navbar is not a requirement but it's great to see you experimenting with it. One thing you could improve is to ensure that it is properly centered, currently in has more empty space on the right side

![image](https://user-images.githubusercontent.com/50066876/236560658-4ae97fbe-3c78-4af1-8e09-00f301b1ffcd.png)

2023-05-05 20:24 UTC, wickathou commented on package.json
[Optional] For your next project, consider using `npm init -y` to initialize your package.json properly

2023-05-06 00:20 UTC, NatiG25 reviewed
## :red_circle: INVALID PULL REQUEST :red_circle: 

## Hi @Etsubdink-Demeke :wave:, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that 
:x: Didn't pass all linter checks
:x: [OPTIONAL] Kindly, create a LICENSE file then add the content present at the README file (License section)  & create a link (MIT) that'll refer to the LICENSE file. This way your README file will match Microverse's README template. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-06 01:33 UTC, Efiamotu-1 requested changes
Hi @Etsubdink-Demeke , 

![](https://camo.githubusercontent.com/a06454929d29b512682cd8b375641b59076b9e5fe1a367808e685e5bcb818de3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a45784e32466d5957466c5a6a45794d7a49314f4455784d5455775a44686b595459355932526c4e6a4d334e7a4e6c4f574530596a4a684d695a6c634431324d563970626e526c636d35686246396e61575a7a583264705a6b6c6b4a6d4e305057632f7a3370696f6b77663057504838314d4f68752f67697068792e676966)

Great work on making the changes requested by a previous reviewer 👏 Your Code is Awesome! 💪
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Especially if that's is your first project 1️⃣. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better job** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 01:33 UTC, Efiamotu-1 commented on index.html
> +    <section id="contact-page">
- [ ] You are yet to implement the requirement made by the previous reviewer provided in this [link](https://github.com/Etsubdink-Demeke/portifolio-desktop-version/pull/1#discussion_r1186466593). The contact me section of your portfolio is not properly centered in relation to the button as well the background image is also not properly placed to reflect closely the given figma design
- [ ] It is important to create your portfolio project in the best possible way to closely match the provided design as this shows your attention to details as a frontend web developer so please kindly work on properly contering the contents of your contact me on desktop version as well as plaving the background images correctly. :+1:

2023-05-06 01:33 UTC, Efiamotu-1 commented on index.html
> +        <div class="cards">
- [ ] The previous reviewers requirement in this [link](https://github.com/Etsubdink-Demeke/portifolio-desktop-version/pull/1#discussion_r1186459734) has also not been implemented. below is the current design of one of your cards on desktop view. please kindly make sure to align the contents of each card properly using the respective css properties as it is always important to keep your project professional and attractive to users and recruiters. :+1:  
- your design
![car-s](https://user-images.githubusercontent.com/89055502/236590624-5340220b-af07-4212-a872-f1955489b510.png)

2023-05-06 01:33 UTC, Efiamotu-1 commented on index.html
- your design on the mobile version is still very inconsistent with the design on figma and as pointed by your previous reviewer in this [link](https://github.com/Etsubdink-Demeke/portifolio-desktop-version/pull/1#discussion_r1186454546). please kindly readjust the styling of your portfolio page on a mobile device to match industry standards of mobile responsive web pages. :+1:

2023-05-06 01:33 UTC, Efiamotu-1 commented on index.html
> +              <ul class="cards__elements--list">
- [ ] please make sure to use the correct font color for the technologies as shown in the figma design below, you can find the correct fonts from the [figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?type=design&node-id=34-848&t=iCVc0ujmBGGSZMXT-0) 
- figma design
![con-f](https://user-images.githubusercontent.com/89055502/236590891-d3801455-17c9-49d7-9d5d-2f83a4c9bd5c.png)
- your design
![con-s](https://user-images.githubusercontent.com/89055502/236590899-2fe408ef-0cd2-4c41-8827-5587ca91b76e.png)

2023-05-06 01:33 UTC, Efiamotu-1 commented on styles.css
- your css styling on line `54` as shown below which gives the nav 100% width is after the overall look of your portfolio on both the mobile and desktop version causing it to overflow the viewport please look into this and make the proper use of the css property to style the desktop version of your project. :+1: 
```
  .nav {
    width: 100%;
  }
```

2023-05-06 08:31 UTC, wayungi requested changes
Hi @Etsubdink-Demeke , 

![image](https://user-images.githubusercontent.com/99656687/234200054-89d3fce4-7f5b-4e07-a92f-9fad90948091.png)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


 ## Highlights
- [ ] All linter checks are passing ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 08:31 UTC, wayungi commented on index.html
> +    </section>
- [ ] This has been highlighted before. I will try and use a diagram to explain the point. Please center the form below the text. 😄 
![form](https://user-images.githubusercontent.com/99656687/236612002-a2ca1861-f5c1-4b9c-a8e0-de85494849c7.png)

2023-05-06 08:31 UTC, wayungi commented on index.html
> +        <div class="cards">
- [ ] Good work in trying to align the contents properly. You have not implemented the space between the image and the content as in Figma. Please look at the illustration below and add the required space. **Note** This applies to all your cards
![card](https://user-images.githubusercontent.com/99656687/236612538-8c498c06-ee1b-415c-9522-7d7fe23b5a3c.png)

2023-05-06 08:31 UTC, wayungi commented on index.html
- [ ] As suggested by the previous reviewer, your page does not fit on the mobile view. Please let work on this using media queries to apply different rule sets based on device width. 😅

2023-05-06 10:28 UTC, shella12 reviewed
Hi <STUDENT_MENTION>, 

#  Status: Invalidated :red_circle: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, 

- [ ] that has linter errors. Please fix the linter errors before submitting for another request

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-06 11:35 UTC, merged